# Site settings
title: Tuobalabala
SEOTitle: Tuo的博客
header-img: img/post-bg-coffee.jpg
email: xht19980305@gmail.com
description: "The moment you think about giving up, think of the reason why you held on so long. "
keyword: "Blog"
url: "https://xht19980305.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xht19980305/xht19980305.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "勿忘初心 方得始终"
sidebar-avatar: /img/about-Vm-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    xht19980305
zhihu_username:     Tuobalabala
#weibo_username:
#twitter_username:   danranVm




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important





# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 571510b202515d39bcc6                            #生成的clientID
  clientSecret: f3784b0ab3e44cc780d87dc023181efd6a7e9759    #生成的clientSecret
  repo: danranvm.github.io    #仓库名称
  owner: danranvm    #github用户名
  admin: danranvm
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: a4ec9dec7dab7324af2a1985cc8470af
# Google Analytics
ga_track_id: 'UA-129162510-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        
    }
]
